spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sit_database
    username: root
    password: sit@csd
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 7070
