spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sit_database
#    url: jdbc:mysql://sitdatabase.c7ou42eg2owg.ap-southeast-2.rds.amazonaws.com:3306/sit_database
    username: root
    password: sit@csd

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 7070